config/routes.rb
Rails.application.routes.draw do
  devise_for :subscribers
  resources :starters
  get 'home/index'
  root 'home#index'
  

end

app/models/starter.rb
class Starter < ActiveRecord::Base
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@starters = Starter.all
  end
end

app/controllers/starters_controller.rb
class StartersController < ApplicationController
  before_action :set_starter, only: [:show, :edit, :update, :destroy]

  # GET /starters
  # GET /starters.json
  def index
    @starters = Starter.all
  end

  # GET /starters/1
  # GET /starters/1.json
  def show
  end

  # GET /starters/new
  def new
    @starter = Starter.new
  end

  # GET /starters/1/edit
  def edit
  end

  # POST /starters
  # POST /starters.json
  def create
    @starter = Starter.new(starter_params)

    respond_to do |format|
      if @starter.save
        format.html { redirect_to @starter, notice: 'Starter was successfully created.' }
        format.json { render :show, status: :created, location: @starter }
      else
        format.html { render :new }
        format.json { render json: @starter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /starters/1
  # PATCH/PUT /starters/1.json
  def update
    respond_to do |format|
      if @starter.update(starter_params)
        format.html { redirect_to @starter, notice: 'Starter was successfully updated.' }
        format.json { render :show, status: :ok, location: @starter }
      else
        format.html { render :edit }
        format.json { render json: @starter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /starters/1
  # DELETE /starters/1.json
  def destroy
    @starter.destroy
    respond_to do |format|
      format.html { redirect_to starters_url, notice: 'Starter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_starter
      @starter = Starter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def starter_params
      params.require(:starter).permit(:headline, :author, :body, :pay)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/starters_helper.rb
module StartersHelper
end

app/views/home/index.html.erb
    <ul class="nav">
       <% if subscriber_signed_in? %>
          <%= link_to "Settings", edit_subscriber_registration_path %>
          <%= link_to "Log Out", destroy_subscriber_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign Up", new_subscriber_registration_path %>
        <%= link_to "Sign In", new_subscriber_session_path %>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->

<div class="center">


<h1>FearTheWave.com</h1>
<p>Home for the blog posts.</p>


<% @starters.each do |starter, index| %>
    <h1><%= starter.headline %></h1>
    <h3><%= starter.author %></h3>
    <p><%= starter.body %></p>
<% end %> 

<%= link_to "New Blog Post", starters_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Storyboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/starters/_form.html.erb
<%= form_for(@starter) do |f| %>
  <% if @starter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@starter.errors.count, "error") %> prohibited this starter from being saved:</h2>

      <ul>
      <% @starter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :headline %><br>
    <%= f.text_field :headline %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, cols: "90", rows: "30" %>
  </div>
  <div class="field">
    <%= f.label :pay %><br>
    <%= f.check_box :pay %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/starters/edit.html.erb
<h1>Editing Starter</h1>

<%= render 'form' %>

<%= link_to 'Show', @starter %> |
<%= link_to 'Back', starters_path %>

app/views/starters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blog Posts</h1>

<table>
  <thead>
    <tr>
      <th>Headline</th>
      <th>Author</th>
      <th>Body</th>
      <th>Pay</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @starters.each do |starter| %>
      <tr>
        <td><%= starter.headline %></td>
        <td><%= starter.author %></td>
        <td><%= starter.body %></td>
        <td><%= starter.pay %></td>
        <td><%= link_to 'Show', starter %></td>
        <td><%= link_to 'Edit', edit_starter_path(starter) %></td>
        <td><%= link_to 'Destroy', starter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Starter', new_starter_path %> <br> <br> 

<%= link_to "Home", root_path %>

app/views/starters/new.html.erb
<div class="center">

	<h1>New Post</h1>

	<%= render 'form' %>

	<%= link_to 'Back', starters_path %>

</div>

app/views/starters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Headline:</strong>
  <%= @starter.headline %>
</p>

<p>
  <strong>Author:</strong>
  <%= @starter.author %>
</p>

<p>
  <strong>Body:</strong>
  <%= @starter.body %>
</p>

<p>
  <strong>Pay:</strong>
  <%= @starter.pay %>
</p>

<%= link_to 'Edit', edit_starter_path(@starter) %> |
<%= link_to 'Back', starters_path %>